### ISSUE TITLE
Publish in Gradle plugin portal

### ISSUE THREAD

**Issue by adamdubiel** [Codearte/gradle-nexus-staging-plugin#10]
This plugin should be published in Gradle plugin portal - now it's really easy (theres an official plugin for that).

**Comment by szpak** [comment]
Better late that never :). Although in the meantime I figured out how to put plugins into the portal releasing artifacts only to Maven Center. The bad is that I will have to upload them to two places which a little bit complicates quasi-transactional releasing from CI.

**Comment by adamdubiel** [comment]
Hm, do you mind sharing? Currently i stopped releasing axion-release to Central, as it involved a lot of hassle.

**Comment by szpak** [comment]
Maybe I'm old-fashioned (a little bit sentimental), but for me Maven Central is the primary (and ultimate :) ) place to keep artifacts. They have strict rules to keep content unchanged after release/promote and it is unlikely that some artifacts just disappear in the future (like in home made JavaScript repositories hosted at GitHub :) ). In Bintray (and probably in the new plugin repository) it is possible to remove or override your own artifacts (accidentally or just to push a fix).
In addition there was a discussion on the PIT mailing list about switching to Bintray completely and there were voices against from the people working in corporations who were allowed only to use artifacts from the Central.

**Comment by jkubrynski** [comment]
@adamdubiel take a look at one of our projects - for example accurest - https://github.com/Codearte/accurest

**Comment by adamdubiel** [comment]
@jkubrynski - i know how to publish "normal" projects, but i'm more interested in using Maven Central with Gradle plugin portal.

@szpak - i agree with these arguments, but on the other hand Central should work a bit on their user experience - creating account via JIRA ticket or little official support for Gradle is a major pain (thankfully there is bmuschko's plugin now).

**Comment by szpak** [comment]
@adamdubiel I agree that Sonatype and Nexus are also old-fashioned and in some aspects unfortunately doesn't conform to "nowadays standards".

**Comment by markslater** [comment]
Did you ever get anywhere with this?  I love the plugin (I still bear the scars from trying to get the equivalent to work in Ant using the Ant Maven task), and being able to pick it up using the new plugin syntax would make it even better.

I see that the plugin publishing plugin still has some ominous comments about dependencies in JCenter, which implies your original objection may still stand... but I though it was worth asking none the less.

**Comment by szpak** [comment]
Not yet. But thanks for your vote.

**Comment by thejohnfreeman** [comment]
Now, can I help with this one? :)

**Comment by szpak** [comment]
Thanks @thejohnfreeman, you have already done enough in https://github.com/szpak/gradle-pitest-plugin/pull/55 :).

I uploaded the latest version to the Plugin Portal. I should be available soon:
> Publishing plugin io.codearte.nexus-staging version 0.5.3
> Thank you. Your new plugin io.codearte.nexus-staging has been submitted for approval by Gradle engineers. The request should be processed within the next 24 hours, at which point you will be contacted via email.

**Comment by szpak** [comment]
It seems that for plugins with custom Maven coordinates, but without previously published artifacts the approval process is much faster:
https://plugins.gradle.org/plugin/io.codearte.nexus-staging
