### ISSUE TITLE
Put project name/version in closed/released repository by default

### ISSUE THREAD

**Issue by szpak** [Codearte/gradle-nexus-staging-plugin#115]
As proposed also in https://github.com/marcphilipp/nexus-publish-plugin/issues/30, the plugin could put the released project groupId/name/version in the staging repository description (instead of "Automatically released/promoted with gradle-nexus-staging-plugin").

**Comment by vlsi** [comment]
Oh, in practice there's `io.codearte.gradle.nexus.NexusStagingExtension#setRepositoryDescription` API to set the description of the repository.

Here's a screenshot from `Staging Repositories` in Central:
<img width="720" alt="staging_comment" src="https://user-images.githubusercontent.com/213894/75625264-92f25600-5bcd-11ea-86df-d46fe51d7147.png">

**Comment by szpak** [comment]
Yes, it was added in 2017. However, it would be good to have it available by default.

Nevertheless, thanks @vlsi for bringing it up for people reaching this issues.

**Comment by szpak** [comment]
TL;TD. It's a default bahaviour of [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin/).

A longer version. To make releasing to Maven Central even easier, I and Marc Phillip (the author of nexus-publish-plugin) combined forces to create a next generation, unified, 2-in-1 plugin - [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin/). It is a recommended solution, as our development effort will be put in that new plugin. See my [blog post](https://blog.solidsoft.pl/2021/02/26/unified-gradle-projects-releasing-to-maven-central-in-2021-migration-guide/) and the official [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo).
