### ISSUE TITLE
Java 13 EA CI server sanity build

### ISSUE THREAD

**Issue by szpak** [Codearte/gradle-nexus-staging-plugin#118]
Once Gradle is capable of running with Java 13 - https://github.com/gradle/gradle/issues/8681.

**Comment by AlanBateman** [comment]
Gradle has been broken on JDK 13 EA builds for more than 6 months. It's is also broken on JDK 14 EA builds for about 2 months.  Continuous testing with the latest JDK EA builds is important if Gradle is to keep up.

**Comment by szpak** [comment]
That's sad, that it's [planned](https://github.com/gradle/gradle/issues/8681#issuecomment-518306735) to be available only in Gradle 6.0 which will be available one day... @AlanBateman Feel free to express your opinion in the aforementioned issue.

**Comment by szpak** [comment]
OpenJDK 15 has been added to the test suite some time ago. Closing.
