### ISSUE TITLE
Could you please migrate to `Property<...>` APIs?

### ISSUE THREAD

**Issue by vlsi** [Codearte/gradle-nexus-staging-plugin#124]
Current APIs require to set properties like `username/password/stagingProfileId/packageGroup/...` no matter if the staging would actually take place or not.

That is I can't treat "missing username" as an error because user might be just building jars.

It would be so much better if I could just pass values via `Property` so it would be queried only when the task was really about to run.
Then I could produce a nicer failure message that would clarify user what went wrong and which property (e.g. in `gradle.properties`) should be configured.

**Comment by szpak** [comment]
Yes, I plan to do that - the new properties already use the new API. However, I will be not backward compatible chance for [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin/issues/21).

**Comment by szpak** [comment]
FYI, based on my experience from migration in my other plugin, the Property API is not as perfect as I will be one day.
See:
 - https://discuss.gradle.org/t/uncheckedioexception-unable-to-store-input-properties-with-regularfileproperty/33086/1
 - https://discuss.gradle.org/t/regularpileproperty-vs-property-file/33074
 - https://github.com/gradle/gradle/issues/10475
 - https://github.com/gradle/gradle/issues/10517
 - https://github.com/gradle/gradle/issues/4311

What's more some of the useful methods were added just in the recently released Gradle 5.6.

**Comment by szpak** [comment]
TL;TD. [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin/) is already using that approach.

A longer version. To make releasing to Maven Central even easier, I and Marc Phillip (the author of nexus-publish-plugin) combined forces to create a next generation, unified, 2-in-1 plugin - [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin/). It is a recommended solution, as our development effort will be put in that new plugin. See my [blog post](https://blog.solidsoft.pl/2021/02/26/unified-gradle-projects-releasing-to-maven-central-in-2021-migration-guide/) and the official [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo).
