### ISSUE TITLE
How to handle DEPRECATION WARNING. The staging repository ID is not provided?

### ISSUE THREAD

**Issue by pwittchen** [Codearte/gradle-nexus-staging-plugin#127]
Hi,

I used Gradle task `closeAndReleaseRepository` and got the warning: 

```
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
```

What should I do? Where should I provide repository ID and what does it really mean?

**Comment by szpak** [comment]
See the [point](https://github.com/Codearte/gradle-nexus-staging-plugin#2-why-my-release-build-on-travis-suddenly-started-to-fail-with-wrong-number-of-received-repositories) in FAQ to add [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin/) to better handle a staging repository resolution.

I will keep the issue open as I plan to rework the FAQ, the error message or even apply the nexus-publish-plugin automatically in a default configuration to make it more natural in reception.

**Comment by pwittchen** [comment]
Do I really need nexus-publish-plugin? I publish artifacts with custom groovy/gradle script and it works well and use gradle-nexus-staging-plugin for closing and releasing the artifacts. I don't want to add another dependency to the project (which I'm not going to use) just to remove the warning. I don't see any benefits from this as I already have working solution :). Maybe I'll wait for updated FAQ.

**Comment by szpak** [comment]
If you are not using Travis (or anything else that sends subsequent requests via different IP addresses) and release on project at the time (+ you manually clean up old staging repositories if anything goes wrong) then GNSP should enough for you (the feature is deprecated and I don't have any intermediate plans to remove it).
However, as described in the FAQ, in [this issue](https://github.com/marcphilipp/nexus-publish-plugin/issues/11) and in [my blog post](https://solidsoft.wordpress.com/2019/02/22/reliable-releasing-to-maven-central-from-travis-using-gradle-2019-edition/) much more reliable is using GNPS together with NPP.

Btw, I rather planned to update FAQ how to start using NPP, not how to suppress the warning :).

**Comment by pwittchen** [comment]
Ok, I'll check it. Thanks!

**Comment by Fleshgrinder** [comment]
I am using [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin) but I still get this whenever I execute `:closeRepository`. I also noticed that the nexus-publish-plugin does not pick up my `nexusUsername` and `nexusPassword` credentials. It seems as if this seamless integration does not work anymore.

**Comment by szpak** [comment]
@Fleshgrinder It should work. Please provide a link to your project. Or, even better, please consider migration to our (my and Marc's) new plugin which - to avoid confusion like your - integrates GSNP and NPP into one plugin - [GNPP](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo).

**Comment by Fleshgrinder** [comment]
[Here you go.](https://github.com/Fleshgrinder/kotlin-case-format/blob/v0.2.0/build.gradle.kts)

Last time I checked the plugin wasn't hosted anywhere but I see that 1.0.0 is out now. Will switch to it. 😊

**Comment by szpak** [comment]
1.0.0 has been released last weekend.

The configuration looks ok. Having a CI job would make it easier to analyze the output.

**Comment by Fleshgrinder** [comment]
I'm in the process of moving from bintray to Central so all this Nexus stuff is new to me so I first want to build up a solid understanding of the workflow before moving to automation. 😉

**Comment by szpak** [comment]
TL;TD. This issue does not occur in [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin/).

A longer version. To make releasing to Maven Central even easier, I and Marc Phillip (the author of nexus-publish-plugin) combined forces to create a next generation, unified, 2-in-1 plugin - [gradle-nexus-publish-plugin](https://github.com/gradle-nexus/publish-plugin/). It is a recommended solution, as our development effort will be put in that new plugin. See my [blog post](https://blog.solidsoft.pl/2021/02/26/unified-gradle-projects-releasing-to-maven-central-in-2021-migration-guide/) and the official [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo).
