### ISSUE TITLE
Cannot promote staging repositories any longer with upgrade of OSSRH

### ISSUE THREAD

**Issue by dcoraboeuf** [Codearte/gradle-nexus-staging-plugin#14]
Hi,

Since the recent update of the Nexus OSSRH from 2.11.1-01 to 2.12.1-01, I cannot promote the staging repositories any longer.

The closing operation works fine, but the promotion operation fails after a few attempts (in my case, after 9 tries out of 31), with an undetermined "Server Error".

All details are in [OSSRH-21248](https://issues.sonatype.org/browse/OSSRH-21248).

Thanks,
Damien.

**Comment by dcoraboeuf** [comment]
As far as I can see, the call fails the first time it tries to call the [`promote`](https://oss.sonatype.org/nexus-staging-plugin/default/docs/path__staging_profiles_-profileIdKey-_promote.html) REST API. According to the documentation, nothing has changed between those versions so that call should be OK.

**Comment by szpak** [comment]
Maybe response from the server changed. Could you run it locally with `--debug` (redirect it to file - there is a lot of text) and paste the response from the server (or anything else you find useful)?

**Comment by dcoraboeuf** [comment]
Doing it now. In the mean time, most of the details are in [OSSRH-21248](https://issues.sonatype.org/browse/OSSRH-21248). But I'm running the close / promotion with the `--debug` option and will attach the output here.

**Comment by szpak** [comment]
`HttpResponseException: Server Error` suggests that server started to return error after n attempts instead of json response with message.

**Comment by dcoraboeuf** [comment]
I've attached the output of the Jenkins job in [gradle-nexus-plugin.txt](https://github.com/Codearte/gradle-nexus-staging-plugin/files/179417/gradle-nexus-plugin.txt).

At line `20583`, the following message kind of implies the error is actually located at OSSRH level.

```
04:59:36.519 [DEBUG] [groovyx.net.http.RESTClient] Response code: 500; found handler: org.codehaus.groovy.runtime.MethodClosure@e599353
```

**Comment by szpak** [comment]
You might ask Sonatype guys if they have an idea (or can check in logs) while accidentally 500 is returned on subsequent (the same) REST call.

**Comment by dcoraboeuf** [comment]
I already did this, waiting for their feedback.

**Comment by szpak** [comment]
As a workaround you could increase `delayBetweenRetriesInMillis` to send requests to Nexus less often (assuming that the error is triggered by number of requests).

**Comment by dcoraboeuf** [comment]
I've added a delay of 10 seconds (instead of 1 second by default) using `delayBetweenRetriesInMillis = 10000` and this seems to solve the issue.

Thanks for the support !
I can close this ticket I think,
Damien.

**Comment by szpak** [comment]
I'm glad it help. Unfortunately that's only a workaround. It would be good to get the answer from Sonatype why the server started to return 500 after upgrade (and make them fix it :) ).
