### ISSUE TITLE
closeAndReleaseRepository passes but the staging repository exists

### ISSUE THREAD

**Issue by abhinayagarwal** [Codearte/gradle-nexus-staging-plugin#147]
We use nexus-publish + nexus-staging to publish and release to Maven Central. 

The Gradle command used for the same is as follows and it **doesn't have** a `--info` flag:
```
./gradlew publish closeAndReleaseRepository
```
We recently tried to [release via Travis](https://travis-ci.com/gluonhq/substrate/jobs/271220568). Both [`closeRepository`](https://travis-ci.com/gluonhq/substrate/jobs/271220568#L10243) and [`releaseRepository`](https://travis-ci.com/gluonhq/substrate/jobs/271220568#L10246) tasks were successful. However, while executing `releaseRepository`, a warning was shown.

```
> Task :closeRepository

Requested operation was executed successfully in attempt 11 (maximum allowed 21)

> Task :releaseRepository

GET request failed. 404: Not Found, body: [errors:[[id:*, msg:No such repository: comgluonhq-1129]]]

Requested operation was executed successfully in attempt 7 (maximum allowed 21)
```
Irrespective of the tasks being successful, the repository was neither closed nor published. Also, what is the reason behind the `GET request failed` warning?

**Comment by szpak** [comment]
> Irrespective of the tasks being successful, the repository was neither closed nor published. 

That's extremely strange. Are you sure that the repository that stayed was comgluonhq-1129 (not any other)?

> Also, what is the reason behind the GET request failed warning?

It's a side effect of the way the plugins checks if the repository was released (so effectively removed from Nexus). You can read more about that [here](https://github.com/Codearte/gradle-nexus-staging-plugin/issues/82#issuecomment-494490890).

Btw, I propose to add `-i` for the deployment tasks to make tracking potential issues easier.

**Comment by abhinayagarwal** [comment]
I will add the `-i` to the deployment task and come back with more information once we do the next release.

**Comment by abhinayagarwal** [comment]
Seems like [this time](https://travis-ci.com/gluonhq/substrate/jobs/273160254) both close and release were successful. Although, both these tasks were called before the actual [closeAndReleaseRepository](https://travis-ci.com/gluonhq/substrate/jobs/273160254#L10394) could be called.

Does `publish` automatically call these tasks?

**Comment by szpak** [comment]
> Although, both these tasks were called before the actual closeAndReleaseRepository could be called.

It's ok. `closeAndReleaseRepository` is an umbrella task which depends on both `closeRepository` and `releaseRepository`. Just to make the call easier.

> Does publish automatically call these tasks?

By default gradle-nexus-staging-plugin's tasks are publish independent. Can be called to close/release also previously created staging repository.

**Comment by abhinayagarwal** [comment]
> It's ok. closeAndReleaseRepository is an umbrella task which depends on both closeRepository and releaseRepository

Things are now clear to me. Thank you for all the help.
