### ISSUE TITLE
Applying the plugin to a library project

### ISSUE THREAD

**Issue by PLNech** [Codearte/gradle-nexus-staging-plugin#16]
## Issue

I'm having an issue applying the plugin to a library project:
- If I follow the instructions, add the `buildscript` dependencies in the root build.gradle and configure via the `nexusStaging` block, then building a project with the library is impossible unless the project using our library has the plugin too:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/projectRoot/myLibrary/build.gradle' line: 37

* What went wrong:
A problem occurred evaluating project ':myLibrary'.
> Could not find method nexusStaging() for arguments [build_b1zw94dj1r82plfo4rpw08r8e$_run_closure2@6b09ab9c] on project ':myLibrary'.
```
- If I instead add the dependencies in myLibrary's build.gradle, everything works fine but every build displays `WARNING. Nexus staging plugin should only be applied to the root project in build.`.
## Questions
- What is the issue with applying the plugin in the library's `build.gradle` rather than the root one?
- Is there a recommended way of applying the plugin for the library's release without forcing every user to apply it to his project too?

**Comment by szpak** [comment]
1. It should be possible. There should be only a warning displayed in the current version. `gradle-nexus-staging-plugin` is not in general module/artifacts specific - it operates on a staging repositories level (it could be even used from the another Gradle project written just to promote some other artifacts). 
2. It could  be done with a conditional apply, inside `if`, activated with a custom `-P` flag. However, have you encountered any practical issue related to applying this plugin?

**Comment by PLNech** [comment]
1. Indeed, there is only the warning displayed, but I wondered if there were other consequences.
2. I'll follow your advice to avoid applying the plugin in default builds. I have not encountered practical issues related to applying the plugin, only this "either have a warning or build fails" situation but which I will resolve thanks to your advice.

Thanks for your help!
