### ISSUE TITLE
staginProfileId not honored

### ISSUE THREAD

**Issue by lamba92** [Codearte/gradle-nexus-staging-plugin#192]
In project [kotlingram](https://github.com/lamba92/kotlingram/) I am trying to publish a Kotlin/Multipaltform project that needs Windows, MacOs and Linux, and uses GitHub Actions to do so (see [`publication_ci.yml`](https://github.com/lamba92/kotlingram/blob/master/.github/workflows/publication_ci.yml)). 

The Nexus Staging Plugin seems to not honor the repository name when creating one with task `createRepository`, instead naming the repository with `comgithublamba92-{random_number}` and ignoring the value `stagingRepositoryId.set(rootProject.name)` set in root [build.gradle.kts](https://github.com/lamba92/kotlingram/blob/master/build.gradle.kts#L22).

I am also using the Nexus Publish Plugin which when executing `gradlew publishToSonatype` do not honor the repository id set by root staging plugin and instead generates a staging repository for each machine. 
 
When invoking `closeRepository` it errors saying:
```text
500: Server Error, body: [errors:[[id:*, msg:Unhandled: Missing staging repository: kotlingram]]]
```

Probably related to [nexus-publish-plugin/#53](https://github.com/marcphilipp/nexus-publish-plugin/issues/53)

**Comment by szpak** [comment]
`publishToSonatype` and `closeRepository` (or `closeAndReleaseRepository`) has to be used in the same call to share stagingRepositoryId. GNSP + NPP don't support releasing from multiple builds and probably will not.

However, I and Marc (the author of NPP) wrote a brand new releasing plugin which also doesn't support it yet, but there is a plan to implement it one day :-). See https://github.com/gradle-nexus/publish-plugin/issues/59 (and https://github.com/gradle-nexus/publish-plugin/issues/19) to comment if it would be sufficient for you (once implemented).
