### ISSUE TITLE
Nexus staging plugin connects to old OSS server. The new one should be https://s01.oss.sonatype.org

### ISSUE THREAD

**Issue by therock24** [Codearte/gradle-nexus-staging-plugin#200]
This plugin is not working for newer modules that are being published, because sonatype is assigning them to the https://s01.oss.sonatype.org staging server, which is the new server.

The plugin still tries to connect to https://oss.sonatype.org, which will not work as the module is not registered on that server.

Can this be changed by any chance to allow setting a different staging repository URL?

**Comment by szpak** [comment]
A default server for the plugin is https://oss.sonatype.org , which is sane as the majority of projects leave there. The new projects use a different server and you - as [described in readme](https://github.com/Codearte/gradle-nexus-staging-plugin#configuration) - can configure the `serverUrl` variable to match your needs. Please let me know, if it is not enough.

**Comment by therock24** [comment]
> A default server for the plugin is https://oss.sonatype.org , which is sane as the majority of projects leave there. The new projects use a different server and you - as [described in readme](https://github.com/Codearte/gradle-nexus-staging-plugin#configuration) - can configure the `serverUrl` variable to match your needs. Please let me know, if it is not enough.

Yea, sorry, didn't properly check the Readme. 
Setting the `serverUrl` to the new server fixed the issue.

I think this should be added to the parameters or FAQ section, something like this:
Important. Users registered in Sonatype after 24 February 2021 need to customize the serverURL:
`serverUrl = https://s01.oss.sonatype.org/service/local/`

Otherwise, the task `closeAndReleaseRepository` will fail with `403: Forbidden`, attempting to connect to the old server.

**Comment by szpak** [comment]
Definitely it is a good idea. Would you like to provide a PR with those changes? :-)

**Comment by therock24** [comment]
> Definitely it is a good idea. Would you like to provide a PR with those changes? :-)

Yea, I was just thinking about it, I will do it. Thanks for the quick reply!

**Comment by szpak** [comment]
Closing as `serverUrl` did a trick and your [PR](https://github.com/Codearte/gradle-nexus-staging-plugin/pull/201) has been merged.

Btw, as you setup a new project, you might want to consider a swtich to a [new plugin](https://github.com/gradle-nexus/publish-plugin/), which is a spiritual continuation of that one. See https://github.com/Codearte/gradle-nexus-staging-plugin/issues/193 .
