### ISSUE TITLE
Unable to close repository

### ISSUE THREAD

**Issue by foxylion** [Codearte/gradle-nexus-staging-plugin#23]
Hi,
I've issues closing my staging repository.

I'm using the maven plugin to deploy the artifacty to OSS.

But when calling `closeRepository` I get a `Bad Request` response from the server. The response contains the following: `Staging of Repository within profile ID='X' is not yet started!`

Any ideas what is missing so that I'm able to call `closeRepository`?

Here is the build log without debuggging: https://travis-ci.org/foxylion/rethinkdb-orm-java/builds/137925647

Manually closing on the web GUI just went fine.

Regards,
Jakob

**Comment by szpak** [comment]
As I see `uploadArchives` is followed directly by `closeRepository`. I suspect that it is just too fast for Nexus to notice that. As a workaround you can divide `uploadArchives` and `closeRepository` into 2 Gradle executions (or introduce an artificial delay between them).

In the situation it is reproducible (the same error in multiple Travis executions) you can also paste the whole server response response - I may consider detecting that response and retry a close operation after some delay.

**Comment by foxylion** [comment]
Hi @szpak,
I've retried later on to manually call `gradle closeRepository` again. It also didn't work, so I suppose that it is not a delay issue. Any other ideas what it could be?

**Comment by szpak** [comment]
My plugin by default set "https://oss.sonatype.org/service/local/" as `serverUrl`. You seem to [use](https://github.com/foxylion/rethinkdb-orm-java/blob/7d5c53ea8d8429bd50c2b0f911ec13b3b3785878/build.gradle#L20) different value. Is it done intentionally? Could you just remove [the assignment](https://github.com/foxylion/rethinkdb-orm-java/blob/7d5c53ea8d8429bd50c2b0f911ec13b3b3785878/build.gradle#L97)?

**Comment by foxylion** [comment]
@szpak That was indeed the problem. Sorry that I bothered you with that issue.
Executing `uploadArchives` and `closeRepository` in one call is no issue. 

Something to note for everyone else: `packageGroup` is not the package where the dependencies live in, it is the group which was assigned to you with writing permissions. In my case that is `de.jakobjarosch` instead of `de.jakobjarosch.someproject`.
