### ISSUE TITLE
did not find secret key for id 'XXXXXXXX' in key source 'file: /home/chao/.gnupg/secring.gpg'

### ISSUE THREAD

**Issue by chaopeng** [Codearte/gradle-nexus-staging-plugin#24]
did not find secret key for id 'XXXXXXXX' in key source 'file: /home/chao/.gnupg/secring.gpg'

but I can see the keyid in `gpg --list-keys`

**Comment by szpak** [comment]
gradle-nexus-staging-plugin has nothing to signing. In fact it even does not upload artifacts. It just asks Nexus to close or promote staging repository which was already created by an upload operation. Please consult the documentation for the [signing plugin](https://docs.gradle.org/current/userguide/signing_plugin.html) and/or maven/maven-publish plugin which you use to upload artifacts.
