### ISSUE TITLE
Deploying multiple artifacts failing

### ISSUE THREAD

**Issue by hakonbo** [Codearte/gradle-nexus-staging-plugin#28]
Hi,

first of all thanks for a great plugin. Using it on our CI/CD server, but have run into an issue. Not sure if it's related to our config or not but the problem arises when there are multiple staging repositories.
I'm getting this error message
```
Execution failed for task ':lib:closeRepository'.
> Wrong number of received repositories in state 'open'. Expected 1, received 2

```

It says there are two repositories in state open, however one of them is closed/released. Support for dropping, #17 , would solve the problem, but maybe there's something else we can do to fix this? 

Thanks,
Håkon

**Comment by szpak** [comment]
`:lib:closeRepository` is suspicious in your quotation. gradle-nexus-staging-plugin should be executed exactly once when all artifacts have been uploaded. Can you release/drop all the repositories in Nexus via GUI, move apply to the root project and call it (`closeAndPromoteRepository`) after the upload?

**Comment by hakonbo** [comment]
Thanks for replying. There is only one artefact being uploaded. With all repositories in Nexus released and dropped, running `uploadArchives` and `closeAndPromoteRepository` from project root works just fine.

But in our case the project is being built on every commit, so in some cases a build is triggered before the previous has been automatically dropped by nexus, and this is when I get the error above. 

You can find our project here https://github.com/wireapp/wire-android-translations and the gradle file here https://github.com/wireapp/wire-android-translations/blob/master/lib/build.gradle should you have a moment to take a look.

**Comment by szpak** [comment]
It looks good in general. Unfortunately I don't have any remedy for that now. There is on my todo list a research if there is a way to correlate artifacts uploading by Gradle with a staging repository which would be helpful in those situations. Gradle doesn't provide that information and I'm not sure if there is any in Gradle plugins internals to get.

Btw, a small suggestion regarding your build.gradle. Defining `group` on the project itself should make redundant doing it 3 times ([1](https://github.com/wireapp/wire-android-translations/blob/master/lib/build.gradle#L63), [2](https://github.com/wireapp/wire-android-translations/blob/master/lib/build.gradle#L100), [3](https://github.com/wireapp/wire-android-translations/blob/master/lib/build.gradle#L135)).

**Comment by szpak** [comment]
Btw, you can subscribe to #29 to get information when/if it is investigated.

**Comment by hakonbo** [comment]
Thanks for your reply, I'll keep an eye on #29 and #17 for now then. Feel free to close this issue.

**Comment by deanhiller** [comment]
yeah, we should close this ticket.  I annotated #29 with a potential solution that I think will work for all these cases as each build would open it's own staging before uploading to that staging location.
