### ISSUE TITLE
releaseRepository FAILED but Succeded

### ISSUE THREAD

**Issue by bartoszwalacik** [Codearte/gradle-nexus-staging-plugin#55]
I'm using latest 0.8.0 version to automate javers releases to Sonatype OSSRH.

So this is a main feature of gradle-nexus-staging-plugin: to release an OSS project to Central via Sonatype Nexus.

In my case, most (I mean more then 70%) releasing build fails. In most cases they are red but succeded.

For example, here is the red but Succeded build:
https://travis-ci.org/javers/javers/builds/233004324

plugin says:
```
Total time: 2 mins 26.62 secs
closeAndPromoteRepository...
:closeRepository
Requested operation wasn't successful in first try. Retrying maximum 10 times with 3 seconds delay between.
:releaseRepository
Requested operation wasn't successful in first try. Retrying maximum 10 times with 3 seconds delay between.
Attempt 11/11 failed. RepositoryInTransitionException was thrown with message 'Repository 'org[secure]-1145' (in 'closed' state) is in transition. Check again later.'. Giving up. Configure longer timeout if necessary.
:releaseRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':releaseRepository'.
> Repository 'org[secure]-1145' (in 'closed' state) is in transition. Check again later.
```

but, surprisingly, release 3.2.0-RC4 was released properly to Sonatype and Staging repository is properly released and closed.

**Comment by szpak** [comment]
Thanks for you report Bartek.

**The short answer**: Increase retrying time. Starting with version 0.7.0 it is 20 times with 2 seconds delay (which is longer than the one set in your config - 10x3s).

**The explanation**. In the past (before 0.7.0) the plugin requested a close or a release operation and when accepted by Nexus didn't care about the result (#21). That operation could fail in the meantime and build could finish successfully having an artifact not closed/released (the opposite to your situation :) ). Starting with 0.7.0 the plugin waits for the operation to finish (retrying and a repo is still "in transition"). As a result the total execution time increased and you hit that problem.

**Possible improvements**. The transition should finish sooner or later (as opposed to missing a repository in a given stay), therefore, the plugin could wait longer for "RepositoryInTransitionException" exception. However, it would complicate the plugin configuration (and internal implementation), so I'm not sure about that.

@bartoszwalacik Please increase the timeout greatly and run it once with `--info` to see exactly after which attempt the repository is released (the number of artifacts increase that time, but 60 seconds should be enough).

**Comment by bartoszwalacik** [comment]
ok, now I have this:

```
//io.codearte.gradle
nexusStaging {
    packageGroup = 'org.javers'
    numberOfRetries = 20
    delayBetweenRetriesInMillis = 3000
}
```

and I have added `--info` to `./gradlew closeAndReleaseRepository` task. Hope it helps.
