### ISSUE TITLE
Wrong number of received repositories in state 'open'. Expected 1, received 86

### ISSUE THREAD

**Issue by seanf** [Codearte/gradle-nexus-staging-plugin#59]
There's only one open staging repository for my groupId org.zanata (repository orgzanata-1177, with the staging profile org.zanata), but in the Nexus UI I can see lots of other open staging repositories, eg central_bundles-10602 from various other OSS projects, all with the staging profile Central Bundles. It's been like that for years, but now I'm wondering if that is normal after all. Should gradle-nexus-staging-plugin skip over the repositories with the generic profile Central Bundles?

**Comment by seanf** [comment]
It appears that my OSSRH credentials weren't accepted, and apparently this caused all the staging repositories to be returned. 

I was trying to use encoded username/password (as supported by one of the Nexus staging Maven plugins), but it seems this isn't supported. When I switched to non-encoded credentials, I got "Possible staging rules violation." as expected.

**Comment by szpak** [comment]
Could you provide the initial output (preferably with `--info`) which was confused for you? Maybe it could be improved.

Regarding do not use plain text password to your Gradle account you can use API key/secret instead (as I [described](https://solidsoft.wordpress.com/2015/09/08/deploy-to-maven-central-using-api-key-aka-auth-token/) it on my blog some time ago).

**Comment by seanf** [comment]
Sorry, I tried but I can't reproduce it now with --info; even the
obfuscated username/password seems to work today.  Perhaps I even generated
them the way you described - it was years ago.

The confusing output was just what I put as the bug title: "Wrong number of
received repositories in state 'open'. Expected 1, received 86". I see now
that there is a meaningful error message when the password is bad, so
apparently my obfuscated credentials *were* working yesterday after all.

As I said, I can't reproduce it - it seems to work as expected now,
whichever password I put in.

Thanks.
