### ISSUE TITLE
Ability to set stagingRepositoryId by external plugin

### ISSUE THREAD

**Issue by szpak** [Codearte/gradle-nexus-staging-plugin#77]
[nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin/) enhances the Gradle publishing mechanism to explicitly create a staging repository. It improves reliability of the release process (see #76 among others).
It would be handy to provide a mechanism to provide the explicitly created repository id by some other plugin instead of trying to determine one looking for its state. It's needed for https://github.com/marcphilipp/nexus-publish-plugin/issues/11.

**Comment by szpak** [comment]
Implemented on the gradle-nexus-staging-plugin side via `stagingRepositoryId` in the plugin extension class.

**Comment by ihostage** [comment]
Hi, @szpak!
Can you share the example of build configuration for using `stagingRepositoryId`?

**Comment by szpak** [comment]
Do you want to set it manually or plan to use https://github.com/marcphilipp/nexus-publish-plugin ?

**Comment by ihostage** [comment]
I try to use `gradle-nexus-staging-plugin` + `nexus-publish-plugin`. But now I have two problems:
* `./gradlew publishToNexus` create two repositories (one implicitly + one explicitly)
* I don't know, how right to use `stagingRepositoryId`

**Comment by ihostage** [comment]
My configuration is next:
* root project:
```
plugins {
    id("io.codearte.nexus-staging") version "0.20.0"
}
...
nexusStaging {
    packageGroup = "org.taymyr"
    username = ossrhUsername
    password = ossrhPassword
}
```
* child project:
```
plugins {
    id("de.marcphilipp.nexus-publish") version "0.1.1"
}
...
nexusPublishing {
    packageGroup.set("org.taymyr")
    username.set(ossrhUsername)
    password.set(ossrhPassword)
}
```

**Comment by szpak** [comment]
You need to wait for https://github.com/marcphilipp/nexus-publish-plugin/issues/11 to be merged and releases. Alternatively you could try to get value (somehow) from nexus-publish-plugin internals and set it in gradle-nexus-staging-plugin's extension with (something like):
```
NexusStagingExtension nexusStagingExtension = 
    project.getRootProject().getExtensions().getByType(NexusStagingExtension.class);
nexusStagingExtension.stagingRepositoryId.set(stagingRepositoryIdFetchSomehowFromNexusPublishPlugin)
```

**Comment by szpak** [comment]
Btw, settings credentials in `nexusPublishing {}` should not be necessary (unless to resolve it in `afterEvaluation {}`). See [this code](https://github.com/marcphilipp/nexus-publish-plugin/blob/master/src/main/java/de/marcphilipp/gradle/nexus/NexusPublishPlugin.java#L71-L78).

**Comment by ihostage** [comment]
Thanks, @szpak! 👍 
After https://github.com/marcphilipp/nexus-publish-plugin/issues/11 to be merged, `stagingRepositoryId` will be set implicitly?
Will not I need to change the build script and just upgrade version of plugin?

**Comment by szpak** [comment]
Just the upgrade of nexus-publish-plugin should be enough (as you already have 0.20.0 of GNSP).

You may also send a friendly ping in https://github.com/marcphilipp/nexus-publish-plugin/issues/11 :)

**Comment by ihostage** [comment]
Already 😂 I link PR for our repository https://github.com/taymyr/lagom-extensions/pull/4 with this issue 😄

**Comment by io7m** [comment]
Quick question: If you're not yet using the `nexus-publish-plugin`, you obviously get this deprecation warning:

```
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
```

Possibly silly question, but does this mean that at some point the `gradle-nexus-staging-plugin` will become impossible to use without the `nexus-publish-plugin`? I'm guessing the answer to that question is *no*, and therefore this means you might implement the explicit staging repository creation directly?

I'm hesitant to pull yet another plugin into the build just to do something I can do in Maven builds without plugins.

**Comment by szpak** [comment]
@io7m, I don't plan to disable "the fallback mode".

As good news, together with @marcphilipp we decided to give the next generation releasing plugin a try - https://github.com/gradle-nexus/publish-plugin/ . Once ready, I will be a replacement for both [GNSP](https://github.com/Codearte/gradle-nexus-staging-plugin/) and [NPP](https://github.com/marcphilipp/nexus-publish-plugin).

**Comment by szpak** [comment]
Btw, unless it changed recently, in the Maven builds you also need a [separate plugin](https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin), just created by the same people as Sonatype Nexus :-).

**Comment by io7m** [comment]
Nice! :+1:
