### ISSUE TITLE
Switch retrying messages to info

### ISSUE THREAD

**Issue by Vampire** [Codearte/gradle-nexus-staging-plugin#82]
Do things like
```
Requested operation wasn't successful in first try. Retrying maximum 20 times with 2 seconds delay between attempts.
```
and
```
Requested operation was executed successfully in attempt 8 (maximum allowed 21)
```
really need to be logged on warning-level?
I would consider them at most info-level.
The first is actually quite common as closing needs ages at least on Sonatype nexus.
The second is a success message and thus not really something to be logged at warning-level and draw attention of the user, don't you think?

**Comment by szpak** [comment]
Thanks for your suggestion, it sounds sensible. I probably made them warnings (preferably lifecycle) to adjust to uploadArchives which was printing "uploading ..." all the time. Since them Gradle has moved forward to provide less verbose output.

I only hope that people "waiting ages" to close/release the project will run it again with `--info` before reporting an issue :).

**Comment by Vampire** [comment]
I see, I never used `uploadArchives`, but always the `maven-publish` plugin, so I never saw this message. :-)

Well, they are perceived ages for such a seemingly easy operation as changing status to closed (I know there are a bunch of checks and so on are run), but actually they are maximum 40 seconds (20*2), so hopefully you will not get too many reports if you degrade to info-level. :-)

**Comment by szpak** [comment]
Initially the values are lower and people with multiproject applications started had some problems (#12). The current values should be fine for most the cases.

I will change it along the way of the next release.

**Comment by szpak** [comment]
Looking at your request unfortunately:
> Requested operation was executed successfully in attempt 8 (maximum allowed 21)

with remain at `warn/lifecycle` level due to #60, until the lower level support will be improved to suppress that particular error/warning 404 message (not in 0.21.0). The first one should be fixed in 0.21.0.

**Comment by Vampire** [comment]
I don't understand, how #60 is related to the success message and why the success message needs to remain on warn/lifecycle level. #60 is about an error message, isn't it, not about the success message.
Also the succes message is on warn level, isn't it? It should at least be degraded to lifecycle level as a success shouldn't be a warning, but imho it should still be lowered to info and not pollute lifecycle logs.
Unless I misunderstood the relation to #60.

**Comment by szpak** [comment]
As mentioned in #60 the following output can be misleading:
```
$ gw releaseRepository
:releaseRepository
Requested operation wasn't successful in first try. Retrying maximum 20 times with 2 seconds delay between.
GET request failed. 404: Not Found, body: [errors:[[id:*, msg:No such repository: infosolidsoft-1066]]]

BUILD SUCCESSFUL
```

"failed" and "successful" next to each other. I would need to suppress all network errors (or moved it to info), add ugly if at the network layer to skip just that error in that particular case or rework the way the error message is propagated up. As I wanted to deliver 0.21.0 as quickly as possible especially for you ;)  I decided to postpone it to the next bunch of changes.

**Comment by Vampire** [comment]
Ah, I see, thanks. :-)
